### ISSUE TITLE
Fails because database.json doesn't exist

### ISSUE THREAD

**Issue by ineffyble** [Linus2punkt0/bluesky-crossposter#10]
There's a check in `jsonRead()` for if the database file actually exists, but none in `isInDB()`. This means that when I try to run, it crossposts, then isInDB() throws, nothing is written, and it repeats on next run.

On a less substantial note it also failed initially because my `logs` and `images` dirs didn't exist, but that was just a case of `mkdir`.

**Comment by Linus2punkt0** [comment]
Whoops, hadn't tried running a clean install of the code in a while. Added a check now!

**Comment by Linus2punkt0** [comment]
Completely missed that you had already made a pull request, still a little green on github.

**Comment by MedPlex98** [comment]
Hey, I have just reinstalled everything and the problem still occurs:

`root@crossposter:~/myapps/crossposter/bluesky-crossposter# python crosspost.py
01/10/2023 02:20:02: Gathering posts

01/10/2023 02:20:02: Posted to twitter

01/10/2023 02:20:04: Posted to mastodon

01/10/2023 02:20:04: Adding to database: {"skeet": "xxx", "ids": {"twitterId": "xxx", "mastodonId": xxx}, "failed": {"twitter": 0, "mastodon": 0}}

Traceback (most recent call last):
  File "/root/myapps/crossposter/bluesky-crossposter/crosspost.py", line 519, in <module>
    updates = post(posts)
  File "/root/myapps/crossposter/bluesky-crossposter/crosspost.py", line 246, in post
    jsonWrite(cid, tweetId, tootId, {"twitter": tFail, "mastodon": mFail})
  File "/root/myapps/crossposter/bluesky-crossposter/crosspost.py", line 407, in jsonWrite
    file = open(databasePath, append_write)
FileNotFoundError: [Errno 2] No such file or directory: '/db/database.json'
(venv) root@crossposter:~/myapps/crossposter/bluesky-crossposter#
`

**Comment by MedPlex98** [comment]
Okay, right. I have now set the path.

But meanwhile I get another error xD

python crosspost.py
Traceback (most recent call last):
  File "crosspost.py", line 1, in <module>
    from atproto import Client
ImportError: No module named atproto


But thanks so far @Linus2punkt0 for your help!

**Comment by Linus2punkt0** [comment]
From what I can see the app is running in "/root/myapps/crossposter/bluesky-crossposter/", but the path specified for logs is "/myapps/crossposter/bluesky-crossposter/logs/", so it can't find the folder.

**Comment by MedPlex98** [comment]
Right, my mistake.
I have now adjusted it and now get the next error. Sorry if I am perhaps a little unknowing 🙈 

root@crossposter:~/myapps/crossposter/bluesky-crossposter# python3 crosspost.py
Traceback (most recent call last):
  File "/root/myapps/crossposter/bluesky-crossposter/crosspost.py", line 517, in <module>
    database = jsonRead()
  File "/root/myapps/crossposter/bluesky-crossposter/crosspost.py", line 418, in jsonRead
    jsonLine = json.loads(line)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

**Comment by Linus2punkt0** [comment]
I'm not entirely sure why you are getting that error but I believe it's because a database-file has been created but is empty. I wrote a small fix that should avoid this error, just download the new version of crosspost.py and try running it again.
