### ISSUE TITLE
Update crossposter to work with latest version of atproto

### ISSUE THREAD

**Issue by Linus2punkt0** [Linus2punkt0/bluesky-crossposter#16]
The atproto library has been updated and the crossposter doesn't work with the new updates. A new version is on the way that will resolve this.

**Comment by Linus2punkt0** [comment]
A new version has now been released.

**Comment by benborges** [comment]
does it also take into account the newly implemented rate limits ?
i'm getting rate limited at first auth oddly

**Comment by Linus2punkt0** [comment]
Bluesky had an issue with their rate-limit implementation which has now been resolved. The crossposter does however not take the rate-limit into account currently, so if you run it more than 300 times a day you will get rate-limited.
