### ISSUE TITLE
Wrong split skeets to tweets

### ISSUE THREAD

**Issue by netfiller** [Linus2punkt0/bluesky-crossposter#33]
Hi, when i post a skeet on Bluesky with 254 words incl. the letters from url to a external site then is the tweet on x splitted to a tweet with 188 words and a reply with 66 words. It is only an example.

Can we fix that?

**Comment by Linus2punkt0** [comment]
I just merged in a version with an improved length calculator, could you check if it solves the issue?

**Comment by netfiller** [comment]
Yes, worked better ;) Now it's okay. Thanx for the script. I love it.
