### ISSUE TITLE
Cross post from Mastodon to the others?

### ISSUE THREAD

**Issue by DJLink** [Linus2punkt0/bluesky-crossposter#39]
Hi, I was wondering if there’s any way to configure it to use one of the other networks as source of posts, for example Mastodon being the primary one and trying to post to the others if possible. Thanks

**Comment by Linus2punkt0** [comment]
It is a possible future addition, though nothing that is prioritized at the moment. Using Mastodon as source is doable, but will need some work. Using Twitter as source is unfortunately impossible at the moment due to the API being partially locked behind a paywall.
