### ISSUE TITLE
Error when checking replies on post

### ISSUE THREAD

**Issue by nathanwentworth** [Linus2punkt0/bluesky-crossposter#4]
Hello! I got this set up with all of my keys, and everything is running the most up to date version, however I'm getting an error on [line 65](https://github.com/Linus2punkt0/bluesky-crossposter/blob/c7a9ea2bf0dde66aa5cfe60abda2d89573ae50b8/crosspost.py#L65C63-L65C63). Seems like it's failing when it's hitting my most-recently posted reply.

```
Traceback (most recent call last):
  File "crosspost.py", line 366, in <module>
    posts = getPosts()
  File "crosspost.py", line 67, in getPosts
    replyToUser = feed_view.reply.parent.author.handle
AttributeError: 'NoneType' object has no attribute 'parent'
```

any help would be appreciated! Thank you for making this!

**Comment by Linus2punkt0** [comment]
Hello! I will take a look. Is it possible for you to send me the URI for the post causing the error? If you add print(feed_view.post.uri) just above the line giving the error it should hopefully print the URI just before failing.

**Comment by nathanwentworth** [comment]
yes! this is the uri: `at://did:plc:ggbnfrk64vwppek4zumorfbc/app.bsky.feed.post/3k4ue2f2lty2t`

**Comment by Linus2punkt0** [comment]
Okay, it seems the issue was caused by some weirdness resulting from the original post in the thread being deleted. I've reworked the code to hopefully deal with any similar problems going forwards! Let me know if everything seems to be working okay with the new version.

**Comment by nathanwentworth** [comment]
Great that fixed it!! I couldn't get it to post to twitter (mastodon works okay), but I'll dig into that myself to make sure I didn't set anything up wrong. Thank you!!!
