### ISSUE TITLE
Posts/Time limit

### ISSUE THREAD

**Issue by Maingron** [Linus2punkt0/bluesky-crossposter#42]
It would be cool to have a feature that allows to set a maximum number of posts per timespan to be posted to Twitter and Mastodon. 
In case the crossposter goes wild for some random reason, maybe because the Bluesky API returns some really weird stuff, we at least wouldn't flood everything for too long.

So let's for example say I'd like to have a post limit of 10 posts per hour, after which the script just won't post anything anymore, to avoid a total floodage in case something goes horribly wrong.

**Comment by Linus2punkt0** [comment]
As mentioned in the other issue, there is already a limit in place to stop spamming, but I will consider adding the possibility to set a max post limit.

**Comment by Linus2punkt0** [comment]
A new version of the crossposter has now been released in a beta branch, which includes settings for max posts per hour. I recommend downloading the beta to a separate folder and transferring settings and databases into the new version.
