### ISSUE TITLE
Posts/Duplicate content limit

### ISSUE THREAD

**Issue by Maingron** [Linus2punkt0/bluesky-crossposter#43]
Pretty much the same idea as #42, except to prevent the same text from being posted every minute or so.
Let's imagine the Bluesky API just returns some weird error in form of a new post with error details under the account's name with every request - sometimes companies do weird stuff.

In that case it'd be cool to not have the crossposter shout the same error at Twitter and Mastodon over and over again.

**Comment by Linus2punkt0** [comment]
There is currently a max limit for retries that can be altered in settings.py. It doesn't limit the total amount of posts in an hour, but it will stop the poster from spamming if something goes wrong.
