### ISSUE TITLE
Sanitizing handles tagged in the original Bluesky post ?

### ISSUE THREAD

**Issue by ywwwes** [Linus2punkt0/bluesky-crossposter#44]
Awesome work which I started to put to good use. Thanks.

One thing I've noticed is that when Bluesky users are tagged in the original post, the handle is currently left as is in the text. When the Bluesky handles are posted to Mastodon or X/Twitter, the behavior can vary:
- if the username doesn't exist, the tag will just display @blueskyusername as text
- if the username exists (one the same Mastodon instance or on X/Twitter), it will tag the corresponding user who may not be the same person / organisation
- there is at least a 3rd scenario where the custom Bluesky handle contains a - (e.g. @dom-ain.com): on Mastodon, it doesn't seem to cause a different behavior but on X/Twitter, since - is not allowed in handles, it will try to tag @ dom if the handle exists

Would it make sense to add a setting to enable a search & replace stripping out the @ from the handles in the original text not to take any chance when posting it to the other networks?

**Comment by Linus2punkt0** [comment]
I have it in my todo to add some options to how bsky usernames are handled, but have not had time to implement it yet. But this is a coming feature!

**Comment by Linus2punkt0** [comment]
A new version of the crossposter has now been released in a beta branch, which includes settings for how to deal with user handles. I recommend downloading the beta to a separate folder and transferring settings and databases into the new version.
