### ISSUE TITLE
Function request: Crosspost to the "Threads" platform

### ISSUE THREAD

**Issue by MedPlex98** [Linus2punkt0/bluesky-crossposter#45]
Since the Threads platform has recently become available on the European market, it would be nice if it could also be included here.

This would clearly highlight the tool, as Bluesky supplies all platforms (Shitter, Mastodon and Threads) with contributions.

Thanks <3

**Comment by Linus2punkt0** [comment]
I'm going to start looking into it! A somewhat major update is in the works, it will hopefully be included there. Aiming for a release in January.

**Comment by enzofrnt** [comment]
> I'm going to start looking into it! A somewhat major update is in the works, it will hopefully be included there. Aiming for a release in January.

The update is far ?

**Comment by Linus2punkt0** [comment]
> > I'm going to start looking into it! A somewhat major update is in the works, it will hopefully be included there. Aiming for a release in January.
> 
> The update is far ?

I'm aiming for within the coming two weeks.

**Comment by Linus2punkt0** [comment]
It appears Threads have threatened legal action towards anyone attempting to create a wrapper for their API, shutting all of the existing projects down. Unfortunately this means that I will not be able to include support for threads in the coming update. If and when the situation changes (I believe Meta has talked about moving towards a more open source protocol in the future) I will add the functionality.
