### ISSUE TITLE
docker image build fails with python:3.11.6-alpine3.18 (no compiler)

### ISSUE THREAD

**Issue by thewikt** [Linus2punkt0/bluesky-crossposter#52]
I attempted installing the crossposter on my Raspberry Pi, running the DietPi distro and using the `Dockerfile` as provided in repo, but I got an error, as the alpine image doesn't contain `gcc`, which is necessary for one of the dependencies of the Python environment to be compiled from source.

Changing the base image to `python:3.11.6` allows the build to complete. 

[docker_compose_up.log](https://github.com/user-attachments/files/16283776/docker_compose_up.log)

**Comment by Linus2punkt0** [comment]
I've set the tag to latest in the dockerfile, there shouldn't be any issue running later versions.
