### ISSUE TITLE
script not creating posts.cache file

### ISSUE THREAD

**Issue by PK1312** [Linus2punkt0/bluesky-crossposter#54]
I feel like I'm probably missing some obvious file permission error or something, but: the problem I'm having is every time I run `crosspost.py`, it says `posts.cache` isn't found, then it says it's gathering posts and saving the cache. But no posts.cache file is ever created. If I create a blank one, the message about it not being found goes away, but it still doesn't actually write anything to `posts.cache`. What am I missing here? My only other theory is that it could be failing to read posts from bluesky, but if that's the case I'm not sure why because I sure did give it my bsky handle and a fresh app password in `settings.py` as the documentation requires.

I'm not using Mastodon at all, for the record.

The output when I run `crosspost.py`, not that i think it's particularly helpful:

```
03/09/2024 19:19:42 (MESSAGE): Reading cache of recent posts.

03/09/2024 19:19:42 (MESSAGE): ./db/post.cache not found.

03/09/2024 19:19:42 (MESSAGE): Gathering posts

03/09/2024 19:19:42 (MESSAGE): Saving post cache.

03/09/2024 19:19:42 (MESSAGE): No new posts found.
```

**Comment by Linus2punkt0** [comment]
Has the folder "db" been created?

**Comment by PK1312** [comment]
whoops, sorry, forgot to reply- yes, the db folder gets created just fine, the issue is `posts.cache` never gets written to, even if it already exists.

**Comment by Linus2punkt0** [comment]
In the exempel given there were no new posts found, so nothing to write to the cache. What does the log say when there are new posts?
